### ISSUE TITLE
Improvement: Use JSONB datatype for columns containing JSON

### ISSUE THREAD

**Issue by jeroenhabets** [hangfire-postgres/Hangfire.PostgreSql#266]
Thanks for your work! We're a happy user :).

One improvement I see is that I noticed TEXT datatype are used throughout for columns containing JSON instead of the more performant JSONB.

Did you consider using JSONB and was something stopping you? Or was JSONB not mature enough at the time you started this driver?

What are your thoughts on migrating to JSONB?

**Comment by jeroenhabets** [comment]
BTW: "Out of the box, Npgsql allows reading and writing these types as strings and provides no further processing to avoid taking a dependency on an external JSON library"
https://www.npgsql.org/doc/types/jsonnet.html

**Comment by frankhommers** [comment]
I am OK with this, good idea. I think Postgres 9 introduced JSONB. Everyone should be running that.
What do you think @azygis , @vytautask & @Plasma ?
If everybody agrees we welcome a PR ;-)

**Comment by azygis** [comment]
To gain the performance benefits of the jsonb column, we would need to also rewrite how we get the job data. Since we just store and retrieve the whole column at runtime, and deserialize it in the app, there would not be much of the difference between text and jsonb. Perhaps only for manual querying directly in the database for debugging purposes, but just for the sake of it - not sure if it's worth it as that can be done via query anyway.

I'm not against changing the data type - just keep in mind that there's possibly no gain in this other than having the "correct" data type.

**Comment by jeroenhabets** [comment]
@azygis I was indeed querying our database looking for slow jobs writing sql like this for `hangfire.state st`:

```	
        CAST((st."data"::json ->> 'PerformanceDuration') AS INT) AS duration,
	CAST((st."data"::json ->> 'Latency') AS INT) AS latency,
```
and repeated in the WHERE clause when I decided to log this ticket.

But actually the real improvement would probably be to make `PerformanceDuration` and `Latency` into separate NULL-able columns. And leave JSONB for the places where the (JSON) structure is varying (e.g. job invocation). This might be even more controversial though if I look at the current data model ;).

I admit that if Hangfire never queries any field in the JSONB columns (don't know TBH) it won't be faster . Querying the database of course will be much user-friendly (see example above) and JSONB enables high performant indexes...though again, IMHO probably best to just extract important fields as separate columns.

Looking forward to hear y'alls thoughts on this.

**Comment by azygis** [comment]
Thing is, these values are not at all relevant to the library - they're needed for the Hangfire itself. Extracting the values to separate columns makes little sense, as we'd then need to retrieve the data from multiple columns, and serialize the data based on how hangfire expects the data. As it is currently, what hangfire gives for us to store, we store, and then retrieve once asked.

I'm fine with changing the column type, but definitely not extracting some columns.

**Comment by frankhommers** [comment]
JSONB is indeed fine. @jeroenhabets, we welcome a PR for this. Be sure to take migration from the current columns into account as well.

**Comment by azygis** [comment]
I'm working on this.

**Comment by jeroenhabets** [comment]
Thanks @azygis !

Does Hangfire.PostgreSql (or Hangfire) have an integration test and/or did you per chance benchmark the insert performance (ideally with a couple of workers polling)? TBH not confident if the result would be flat-out positive.

> To gain the performance benefits of the jsonb column, we would need to also rewrite how we get the job data.

One that note, did you end up rewriting getting the job data? (At first glance I did not see it in PR #298)

**Comment by azygis** [comment]
Sorry, no benchmarks of the sort. From the storage perspective, the impact in performance is trivial since we still send the strings and retrieve the strings. Sadly, Hangfire's `SerializationHelper` can serialize the invocation data/arguments to an empty string for expressions, so we always have to write them as proper JSONs, meaning some ifs are in action.

And no, no bug rewrite, as we did not split any columns in any way. Whatever Hangfire asks to store, we just store, as I said previously.

**Comment by jeroenhabets** [comment]
> And no, no bug rewrite, as we did not split any columns in any way. Whatever Hangfire asks to store, we just store, as I said previously.

Though I would have welcomed a column split it was already clear to me up thread that [split columns had been rejected](https://github.com/hangfire-postgres/Hangfire.PostgreSql/issues/266#issuecomment-1288146274) (and why) in favor of [a Text->JSONB only PR](https://github.com/hangfire-postgres/Hangfire.PostgreSql/issues/266#issuecomment-1465246806) like yours. As a grateful user that's appreciated and I had no intention to reopen that debate 😃.

That said @azygis you yourself wrote that "To gain the performance benefits of the jsonb column, we would need to also rewrite how we get the job data." in a previous [comment](https://github.com/hangfire-postgres/Hangfire.PostgreSql/issues/266#issuecomment-1275653410). 
Hence my question was more if you'd rewritten "how we get the job data" to "gain the performance benefits of the jsonb column" in this [PR](https://github.com/hangfire-postgres/Hangfire.PostgreSql/pull/298)? 
Without having explored your remark in detail, at the time I imagined certain "get jobs" queries to, probably greatly, benefit from having a JSONB column (i.e. WHERE clause).

@azygis again your work and PR are appreciated 🚀 🙇‍♂️ !

**Comment by azygis** [comment]
Ah, now I got ya! No, that hasn't been changed as I was really running out of time. I'm still planning on doing it, though, just later when some other stuff is out of my hair 😉
