### ISSUE TITLE
UpdateCountLock does not timeout

### ISSUE THREAD

**Issue by kgipas** [hangfire-postgres/Hangfire.PostgreSql#273]
Currently `UpdateCountLock` does not have any implementation for lock timeout, like the other locking method `TransactionLockHandler` does.

This can cause issues, for example:
If an instance that's using `UpdateCountLock` is stopped ungracefully while recurring jobs are locked, the lock will never be released. Thus, no recurring jobs will be run, until the lock is manually removed from the database, or the locking method is switched.

**Comment by frankhommers** [comment]
Are  you able to submit a correcting PR for this?
