### ISSUE TITLE
Incorrect versioning in Nuget feed

### ISSUE THREAD

**Issue by maksimnarkevichdp** [hangfire-postgres/Hangfire.PostgreSql#299]
The version **1.19.11** was released right after **1.9.10**, is it expected?

![image](https://user-images.githubusercontent.com/89984275/224673946-bb63f3f1-57b8-4119-b50a-c36612f321a5.png)

**Comment by azygis** [comment]
[Yes](https://github.com/hangfire-postgres/Hangfire.PostgreSql/releases).

**Comment by maksimnarkevichdp** [comment]
How's that? @azygis 
![image](https://user-images.githubusercontent.com/89984275/224675488-af3a5be2-2acf-4f2a-96f8-c875d4ca9a31.png)

**Comment by azygis** [comment]
Oh shoot! I misread the versions.

**Comment by azygis** [comment]
@frankhommers my suggestion is to continue as it is, just renaming the latest releases. Unlisting from nuget, retagging is quite cumbersome. Would that be okay with you?

Honestly not sure how I managed to add not one, but **two** wrong tags.

**Comment by azygis** [comment]
Since some of the projects have already used the newer versions based on the download counters, I'm reluctant to unlist them. Closing the issue and admitting defeat.

Next version will be 1.20.0 when I'm done with #278.

@maksimnarkevichdp thanks for pointing this out!
