### ISSUE TITLE
Hangfire 1.8: First-class Queue Support

### ISSUE THREAD

**Issue by jeroenhabets** [hangfire-postgres/Hangfire.PostgreSql#303]
Hangfire 1.8 is in RC3 and I was wondering if this storage supports this new [First-class Queue Support](https://www.hangfire.io/blog/2023/03/30/hangfire-1.8.0-rc3.html#first-class-queue-support) feature as it contains a clear [Storage Support Required](https://www.hangfire.io/blog/2023/03/30/hangfire-1.8.0-rc3.html#storage-support-required) warning.

I couldn't find anything about it in the release notes. If you transparently store whatever Hangfire throws at you, perhaps no code/schema change is needed.

Perhaps good to clarify this in an upcoming release note? (Or add support in scope of this ticket if a change is needed)

**Comment by azygis** [comment]
No support for new 1.8 features regarding new methods. There's [quite a few](https://github.com/HangfireIO/Hangfire/releases/tag/v1.8.0-rc1), not just the queueing itself.

Unfortunately, I personally don't see myself going through all the changes in the near future (it really depends on free time, which I don't have a lot currently), hopefully there's will and time from someone else.

**Comment by azygis** [comment]
I'm not sure about the _schema_ changes. Depends on whether the job queue gets serialized into the data or is supposed to be saved as a separate column, I did not have time to look through the actual changes. But indeed, the _code_ will need changes as the features need to be "broadcasted" (read: set on the storage itself) for the new queueing way to work.

According to their release notes, only the new features should throw an exception if the feature is not set to be supported by the storage (which by default returns `false`, as in, not supported). Based on that information, it is probably safe to upgrade using the current version of storage, as long as you don't start using the new overloads before the package is updated fully here.
