### ISSUE TITLE
High volume of transactions per second with multiple workers

### ISSUE THREAD

**Issue by Tinyakov** [hangfire-postgres/Hangfire.PostgreSql#306]
I'm using 3 Hangfire servers within a single application instance, each server assigned to a specific queue. Two of these servers have one worker each, while the third has 10 workers, making a total of 12 workers. The QueuePollInterval has been set to 1 second.

The problem is in count of transaction to database. Even with almost no jobs queued, there are approximately 150 TPS being made.

The most commonly used SQL query is as follows:
```
UPDATE "hangfire"."jobqueue" 
SET "fetchedat" = NOW()
WHERE "id" = (
  SELECT "id" 
  FROM "hangfire"."jobqueue" 
  WHERE "queue" = ANY ($1)
  AND "fetchedat" < NOW() + INTERVAL '-1800 SECONDS'
  ORDER BY "queue", "fetchedat", "jobid"
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
RETURNING "id" AS "Id", "jobid" AS "JobId", "queue" AS "Queue", "fetchedat" AS "FetchedAt"
```

I tried to set EnableLongPolling in PostgreSqlStorageOptions, but I didn't notice any difference.

Is this a normal behaviour for Hangfire.PostgreSql provider?

**Comment by azygis** [comment]
Yes, it is normal. There is also locking, unlocking, all sorts of things happening in the background. If this actually creates any problems, feel free to reopen, but just the number of transactions per second is not a problem on it's own.
