### ISSUE TITLE
migrating form ahydrax/Hangfire.PostgreSql

### ISSUE THREAD

**Issue by adnan-kamili** [hangfire-postgres/Hangfire.PostgreSql#307]
I guess few years ago this project was not being maintained, and we had to use the forked project:

https://github.com/ahydrax/Hangfire.PostgreSql

Now, I see the original project is back in action and the fork seems to be unmaintained. I would like to migrate to this project, I am using .net 7 (and fork doesn’t support that yet).

Unfortunately, just changing the nuget package name didn’t help, and I see following exceptions:
```
Npgsql.PostgresException (0x80004005): 42P01: relation "hangfire.counter_id_seq" does not exist
...
Exception data:
    Severity: ERROR
    SqlState: 42P01
    MessageText: relation "hangfire.counter_id_seq" does not exist
    Where: SQL statement "ALTER SEQUENCE "hangfire".counter_id_seq AS bigint MAXVALUE 9223372036854775807"

Npgsql.PostgresException (0x80004005): 42P07: relation "aggregatedcounter" already exists
...
Exception data:
    Severity: ERROR
    SqlState: 42P07
    MessageText: relation "aggregatedcounter" already exists
    File: heap.c
    Line: 1202
    Routine: heap_create_with_catalog

Execution ExpirationManager is in the Failed state now due to an exception, execution will be retried no more than in 00:00:25
Npgsql.PostgresException (0x80004005): 42703: column "id" does not exist
```

Any help you can offer?

**Comment by azygis** [comment]
You will have to manually migrate the database by comparing the scripts in both libraries. All the scripts from `src/Hangfire.PostgreSql/Scripts` folder can be run with whatever query runner you have (pgAdmin, HeidiSQL, etc), you just have to manually change the schema version afterwards to match the current version.

**Comment by adnan-kamili** [comment]
Thanks for the quick response. Our customers deploy our app on their own premises, so running scripts is not a feasible option for us.

Dropping the schema does seem like an option, any check you can help us with this so we can write an idempotent migration for dropping the schema? So we don’t end up dropping it every time on our customers on-premise deployments.

**Comment by azygis** [comment]
What's the process of the deployment? And are you able to ship multiple releases in sequence, making sure they both are run one after the other?

**Comment by adnan-kamili** [comment]
What's the process of the deployment? Docker Compose and Kubernetes

And are you able to ship multiple releases in sequence, making sure they both are run one after the other?

No, users can skip releases.

**Comment by adnan-kamili** [comment]
Thanks for the suggestion. I guess an easier solution is to leave Schema/hangfire as such and use a different Postgres schema name (if that can be configured). Hangfire creates all its tables in a schema named `hangfire`. I can change it to hangfire2. 

So is there any configuration option to change that?

**Comment by azygis** [comment]
Indeed, I really didn't think about just leaving the schema be!

There's an options class when calling `.UsePostgreSqlStorage()`. It contains the property `SchemaName`. Set that and you have your solution. :)

**Comment by adnan-kamili** [comment]
I tried following didn't work:

 config.UsePostgreSqlStorage($"{Configuration.Get<AppOptions>().Database.Url};Search Path=hangfire_data"));

**Comment by azygis** [comment]
No, we don't work with search path. It's `.UsePostgreSqlStorage(connectionString, new PostgreSqlStorageOptions { SchemaName = "hangfire_data" });`.

**Comment by adnan-kamili** [comment]
Thanks it solved the issue
