### ISSUE TITLE
Dashboard graph empty after upgrading 1.9.9 -> 1.19.12

### ISSUE THREAD

**Issue by aamir0** [hangfire-postgres/Hangfire.PostgreSql#308]
Hangfire: 1.7.32
Hangfire.AspNetCore: 1.7.32
Hangfire.Dashboard.BasicAuthorization: 1.0.2
Hangfire.PostgreSql: 1.19.12
.NET: 6.0.16

After upgrading Hangfire.PostgreSql from 1.9.9 to 1.19.12 recently, my dashboard graphs always appear flat. Others on my team have seen it show jobs briefly after they are completed, but then they disappear from the graph (perhaps after an hour has passed).

I didn't upgrade any other Hangfire packages, but am willing to if that addresses the issue. From #303, I see that the newly-released Hangfire 1.8.0 isn't yet supported, but 1.7.34 does exist.

Old:
![image](https://user-images.githubusercontent.com/3621093/235162003-b3d5b3ea-0da4-480e-9ee4-6a26e125dce1.png)

New, shortly after jobs complete:
![image](https://user-images.githubusercontent.com/3621093/235162637-1ac617c2-1d20-4966-8c70-762c7c490d6e.png)

New, after some time:
![image](https://user-images.githubusercontent.com/3621093/235162109-29d1a94f-4680-4f93-a530-7186e0401477.png)

**Comment by azygis** [comment]
These graphs are populated by the counters table. Once in a while, counters table needs to be "cleaned up" so it doesn't become a big monstrosity and for that in [v1.9.10](https://github.com/hangfire-postgres/Hangfire.PostgreSql/releases/tag/1.9.10) a counters aggregator has been introduced. After the counters are aggregated, they are no longer in the counters table, hence no longer visible in the graphs.

If you want to keep them in the graph for longer, I suggest increasing the `PostgreSqlStorageOptions.CountersAggregateInterval` to an appropriate interval (default is 5min).

**Comment by aamir0** [comment]
Thanks! That appears to have worked.

5 minutes feels a bit aggressive given that the default view on the dashboard page shows 1 day of history, but I'll try to remember to override it going forward.
