### ISSUE TITLE
Hangfire PostgreSql Azure not working

### ISSUE THREAD

**Issue by gusleo** [hangfire-postgres/Hangfire.PostgreSql#310]
My application is working well locally, but after publishing to Azure it shows an error like below
![Screenshot_185](https://github.com/hangfire-postgres/Hangfire.PostgreSql/assets/15825376/c9ff456a-991c-477c-a55e-1633061d33c6)

I'm using .NET Core 6 and respective Hangfire. This is a snippet of my code at Program.cs
`string connString = builder.Configuration.GetConnectionString("DefaultConnection") ?? "";
#region Hangfire
builder.Services.AddHangfire(configuration => configuration
    .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
    .UseSimpleAssemblyNameTypeSerializer()
    .UseRecommendedSerializerSettings()
    .UsePostgreSqlStorage(connString));
// add hangfire server
builder.Services.AddScoped<IBackgroundTask, BackgroundTask>(); //one kalbe background task
builder.Services.AddHangfireServer();`

Maybe anyone is facing the same issue and resolved, please share
Thanks

**Comment by azygis** [comment]
Based on the exception you've set an unknown hostname in your connection string. Either set a direct IP address or verify that you have actually set the correct host according to your services.

**Comment by gusleo** [comment]
yes, sorry for this issue. I recreate my Azure services and working well. One day struggling with this issue, no code change needed. thanks
