### ISSUE TITLE
Automatic retry on npgsql network issue.

### ISSUE THREAD

**Issue by latop2604** [hangfire-postgres/Hangfire.PostgreSql#311]
In my environment I have recurring network issue between hangfire and pg and I would like to know if they is a feature available for automatic handling of transient error?

They are something in the entity framework npg provider. But I don't know if EF is used here [Execution Strategy](https://www.npgsql.org/efcore/misc/other.html#execution-strategy).

They are also a closed issue about transitient pg error code [here](https://github.com/npgsql/npgsql/issues/1495)

Thank you for your time

**Comment by azygis** [comment]
Hangfire itself has an [`AutomaticRetryAttribute`](https://docs.hangfire.io/en/latest/background-processing/dealing-with-exceptions.html). It wouldn't be wise for us to retry anything implicitly even for transient errors as we can't be sure about the actual state of your job, it's up for you to decide whether it's safe to fully retry the job or not.
