### ISSUE TITLE
Cannot delete from table "lock" because it does not have a replica identity and publishes deletes

### ISSUE THREAD

**Issue by Shaddix** [hangfire-postgres/Hangfire.PostgreSql#312]
We got the following error after enabling replication in our PostgresDB.
```
hangfire:job:4380181:state-lock: Failed to remove lock
{
exception_message: 55000: cannot delete from table "lock" because it does not have a replica identity and publishes deletes
}
```

Seems that the `lock` table has no primary key, so the replication fails. Btw, as far as I see, it has unique index `lock_resource_key`, so in the meantime we just ran `ALTER TABLE hangfire."lock" REPLICA IDENTITY USING INDEX "lock_resource_key";` which I believe will fix the issue

**Comment by Shaddix** [comment]
I could provide a PR that fixes this if @azygis you are ok with that.

I see 2 possible ways to do that, in both ways it'll be just a matter of adding a SQL script to `Scripts` folder. So, we could either:
1. Make `resource` column a PRIMARY KEY in table `lock`. That seems the most obvious way, but maybe there's a reason why `lock` table doesn't have a PK.
2. `ALTER TABLE hangfire."lock" REPLICA IDENTITY USING INDEX "lock_resource_key";`

@azygis what would you prefer?

**Comment by azygis** [comment]
Let's keep it PK-less - `REPLICA IDENTITY` should be good in my opinion. PK on this table which is constantly written to/deleted from would serve no purpose outside of repl.

It would be good if you were able to test it on your side by running the tests using replication, if you haven't done that yet. Our CI will verify the "usual" workflow with a single instance.

**Comment by zhanghaiboshiwo** [comment]
I had the same problem

**Comment by azygis** [comment]
The package has been [published](https://nuget.info/packages/Hangfire.PostgreSql/1.19.13).
