### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Rast1234** [hangfire-postgres/Hangfire.PostgreSql#314]
Hey. I think i am missing something, but can't find any documentation related to:

## PostgreSqlStorageOptions

Particularly, what is `DistributedLockTimeout` and how does it correlate to `InvisibilityTimeout`? I was only able to find some discussions related to jobs running more than once and issues about locks being held up to said timeout. As far as i understand, invisibility timeout is what prevents an abandoned job from being indefinetly stale. What's the purpose of distributed lock then?

Some other options are similar to other hangfire storage drivers and i could figure out what they are for, but not sure if postgresql driver works differently with specifics, eg how transactions are done. Which brings me to:

## Overall overview

It'd be nice to get an idea how things are done in the driver, eg. how transactions are handled, what are the main differences (if any) with mssql hangfire driver, etc. I am concerned about details because hangfire's docs are not very specific too and its design doesn't give much guarantees, leaving a lot of corner cases to be figured out by experiments:

* What is the time limit for a job? Is it configured on a storage level? I am observing now that it's controlled by invisibility timeout, in a weird way that same job gets picked up second time and then both instances (long-running and newly started) get canceled
* How transactions are held/released? I access db via `pgbouncer` which may be limiting. Also, postgres cluster itself doesn't like long-running transactions because of replication. Would be great to know if there are any assumptions in the driver regarding connection persistency, transaction length, etc

---

I am happy to write docs regarding all of that but i'm not familiar with internals so maybe we can discuss it all here and i'll compile them into documentation, what do you think?

**Comment by frankhommers** [comment]
We maintain this project in our free time. And I currently lack the time to write docs.

But I feel like some questions could be answered because their logic is inherited from Hangfire.SqlServer .. So yeah, it would be nice to extract as much info as possible from that component. If you make a doc for us to review (with your assumptions) that'll save us time.
