### ISSUE TITLE
Queue priorities?

### ISSUE THREAD

**Issue by JanmanX** [hangfire-postgres/Hangfire.PostgreSql#315]
I want to prioritize my queues. For instance, jobs in queue "A" get priority, whereas jobs in queue "B" are run only when there are no jobs left in queue "A".

Is this possible in this implementation?

**Comment by dmitry-vychikov** [comment]
Yes, it is possible. You need to pass a list of queues to your background hangfire server.

Then it will process jobs in the alphabetical order by queue name. In other words, it is the name of the queue which affects ordering.

Also, don't forget about default queue.

**Comment by JanmanX** [comment]
Aha, thanks @dmitry-vychikov :)
