### ISSUE TITLE
Warning for dependency Newtonsoft.Json 11.0.1

### ISSUE THREAD

**Issue by vicenteyu** [hangfire-postgres/Hangfire.PostgreSql#335]
https://github.com/advisories/GHSA-5crp-9r3c-p9vr

**Comment by azygis** [comment]
We don't have an explicit dependency on Newtonsoft.Json, it comes from Hangfire itself. You should report the issue [there](https://github.com/HangfireIO/Hangfire/issues).

For what is worth, setting a version in your own projects should just work and use a newer version without any patching of external references
