### ISSUE TITLE
Using in PostgreSqlStorage 

### ISSUE THREAD

**Issue by maximiliysiss** [hangfire-postgres/Hangfire.PostgreSql#339]
Hello!
Is it normal that there is no `using` statement in PostgreSqlStorage (https://github.com/hangfire-postgres/Hangfire.PostgreSql/blob/master/src/Hangfire.PostgreSql/PostgreSqlStorage.cs#L89) for PrepareSchemaIfNecessary

```charp
public PostgreSqlStorage(IConnectionFactory connectionFactory, PostgreSqlStorageOptions options)
{
  _connectionFactory = connectionFactory ?? throw new ArgumentNullException(nameof(connectionFactory));
  Options = options ?? throw new ArgumentNullException(nameof(options));

  if (options.PrepareSchemaIfNecessary)
  {
	NpgsqlConnection connection = CreateAndOpenConnection();
	try
	{
	  PostgreSqlObjectsInstaller.Install(connection, options.SchemaName);
	}
	finally
	{
	  if (connectionFactory is not ExistingNpgsqlConnectionFactory)
	  {
		connection.Dispose();
	  }
	}
  }

  InitializeQueueProviders();
}
```

**Comment by azygis** [comment]
Yes, it is. `using` is basically syntactic sugar for `try {} finally {}`, and if you take a closer look, we are disposing of the connection only if an existing connection factory is used (in other words, we are not supposed to dispose of connections not created by us).

**Comment by frankhommers** [comment]
`using (something)` is doing this: `var something; try { something = new(); } finally { something.Dispose() }`;

@azygis missed `Dispose` in his finally block  ;-)

**Comment by azygis** [comment]
That's what I get in a hurry. Indeed, forgot to write it out.

But to be fair, `using` does NOT do anything like `new()` so your example is not entirely right either 😅

```

using (var something = new Something())
{
    something.Do();
}
```
becomes
```
var something = new Something();
try
{
    something.Do();
}
finally
{
    something.Dispose();
}
```

Which, in our case, is not what we want all the time, so we are not using `using` (hehe) in that case.

With that, I'm never again writing code on my phone. It takes way too much time. 😅
