### ISSUE TITLE
Unable to run the solution as is in .NET 8

### ISSUE THREAD

**Issue by pradeepradyumna** [hangfire-postgres/Hangfire.PostgreSql#345]
Downloaded the solution from here[ https://github.com/hangfire-postgres/Hangfire.PostgreSql/releases/download/1.4.8.1/aspnetcore_hangfire_sample.zip]( https://github.com/hangfire-postgres/Hangfire.PostgreSql/releases/download/1.4.8.1/aspnetcore_hangfire_sample.zip) but unable to run it on .NET 7 or .NET 8

**Comment by azygis** [comment]
Yep, not much I can tell here. Do not use it. We are not maintaining the example solution as evident from the release version.

Will remove it from readme.

**Comment by azygis** [comment]
Removed with 07c5815.
