### ISSUE TITLE
How to migrate obsolete PostgreSqlBootstrapperConfigurationExtensions usage

### ISSUE THREAD

**Issue by Herdo** [hangfire-postgres/Hangfire.PostgreSql#356]
The most methods in `PostgreSqlBootstrapperConfigurationExtensions` are flagged as obsolete for version 2.0.0 of this library.
However, the successor doesn't provide the configuration capabilities to configure stuff like `SchemaName`, `PrepareSchemaIfNecessary`, `DistributedLockTimeout`, etc.

What's the plan to configure these settings in the future if everything there is private?

**Comment by azygis** [comment]
There's another overload for passing the `PostgreSqlStorageOptions` as the next argument when registering the storage, same way as the old methods.

**Comment by azygis** [comment]
@Herdo check [this one](https://github.com/hangfire-postgres/Hangfire.PostgreSql/blob/ab5f94c67ce6d2a7c5fa244396d2a20dd8c989cd/src/Hangfire.PostgreSql/PostgreSqlBootstrapperConfigurationExtensions.cs#L131).
