### ISSUE TITLE
EnableHeavyMigrations missing from PostgreSqlStorageOptions

### ISSUE THREAD

**Issue by rasmusbuchholdt** [hangfire-postgres/Hangfire.PostgreSql#359]
## EnableHeavyMigrations property missing in PostgreSqlStorageOptions for Hangfire 1.8 upgrade

**Description:**  
I am currently upgrading Hangfire from version 1.7 to 1.8 and following the [official guide for automatic schema migration](https://docs.hangfire.io/en/latest/upgrade-guides/upgrading-to-hangfire-1.8.html#automatic-migration). The documentation suggests using the `EnableHeavyMigrations` property. However, this property does not appear to be available in `PostgreSqlStorageOptions`.

**Steps to Reproduce:**
1. Upgrade Hangfire to version 1.8.
2. Attempt to set `EnableHeavyMigrations` within `PostgreSqlStorageOptions`.

**Expected Behavior:**  
The `EnableHeavyMigrations` property should be available and settable in `PostgreSqlStorageOptions` to allow for automatic schema migrations.

**Actual Behavior:**  
The `EnableHeavyMigrations` property is not found in `PostgreSqlStorageOptions`.

**Comment by azygis** [comment]
It's missing because it's not in PostgreSQL storage provider. You're following documentation which uses SQL Server storage provider which is indpendent from this package (and vice versa).
