### ISSUE TITLE
1.8 migration guide

### ISSUE THREAD

**Issue by domagojmedo** [hangfire-postgres/Hangfire.PostgreSql#363]
https://docs.hangfire.io/en/latest/upgrade-guides/upgrading-to-hangfire-1.8.html

Is there anything like this available for postgres storage? 

For example I found https://github.com/hangfire-postgres/Hangfire.PostgreSql/issues/359 which asks about EnableHeavyMigrations option which is in the guide. 
I see it's not used here but do we just skip that in migration then or?

Thank you

**Comment by azygis** [comment]
Yes, you just skip the parts of migration that is relevant only for SQL Server.
