### ISSUE TITLE
Implement the List-returning GetFirstByLowestScoreFromSet

### ISSUE THREAD

**Issue by shokanson-extensiv** [hangfire-postgres/Hangfire.PostgreSql#368]
In a conversation with Sergey Odinokov regarding the new [scheduler parallelism support in Hangfire.Core 1.8.12](https://github.com/HangfireIO/Hangfire/releases/tag/v1.8.12), he suggested this to allow Hangfire.PostgreSql to support it:

> The method that's required to be implemented is the `GetFirstByLowestScoreFromSet` that returns `List<string>` instead of a single value, which is already implemented. [This is the implementation](https://github.com/HangfireIO/Hangfire/blob/ead95d13f33515934ed44e0f89ed0007c686237a/src/Hangfire.SqlServer/SqlServerConnection.cs#L378-L393) in `SqlServerConnection`, and in fact, the implementation in PostgreSQL for a single value is already [implemented here](https://github.com/hangfire-postgres/Hangfire.PostgreSql/blob/dcb57189e2cce36f2c0bf5e6a7e1ecda3b0f1d8d/src/Hangfire.PostgreSql/PostgreSqlConnection.cs#L304C28-L325). So the new implementation should only change `QuerySingleOrDefault` to `Query` and remove the `LIMIT` clause in the query itself.

(I think the last part is incorrect because the `LIMIT` clause should remain, but instead of `1` use the provided `count`.)

I have made the changes in a local repo and would like to submit a PR for review. Should I fork this GitHub repo and submit a PR from my fork? Or should I push a feature branch to this repo and submit the PR from there?

**Comment by azygis** [comment]
You cannot push to this repo directly while not being a collaborator/member. Please create a PR from a fork.

**Comment by azygis** [comment]
Thank you! And sorry for the long wait.

**Comment by shokanson-extensiv** [comment]
No problem. Thank you for accepting my contribution.
