### ISSUE TITLE
How do we roll back if there is an issue?

### ISSUE THREAD

**Issue by tysonstewart** [hangfire-postgres/Hangfire.PostgreSql#379]
I'm looking to upgrade from version 1.9.9 to a more recent version. It seems that there is at least one breaking schema change along the way (`servers` table, `data` column changes from text type to jsonb). That's fine if everything goes well with our deployment, but what if we need to roll back? What's the suggested strategy for this scenario?

**Comment by azygis** [comment]
Make a backup of the schema manually before upgrading and restore it if something goes wrong.

Not sure if `servers.data` type change is considered a breaking change. It's breaking only if you ever manually read the column outside of provider, or you changed it manually to something that is not a valid JSON. If that's the case, server would not start.

**Comment by tysonstewart** [comment]
> Make a backup of the schema manually before upgrading and restore it if something goes wrong.

The concern I have with this is that we schedule new jobs frequently, so I assume if we have to restore from a backup, we'll lose whatever jobs were created in the meantime.

> Not sure if servers.data type change is considered a breaking change. 

Code before the upgrade (i.e. what we'd have to roll back to) throws an exception on startup which is what prompted me to create this issue.

**Comment by frankhommers** [comment]
I'd urge you to test all scenarios before deploying to production.
We don't have an 'down' mechanism for this. If you want this, we are happy to accept a PR.

**Comment by azygis** [comment]
> > Make a backup of the schema manually before upgrading and restore it if something goes wrong.
> 
> The concern I have with this is that we schedule new jobs frequently, so I assume if we have to restore from a backup, we'll lose whatever jobs were created in the meantime.

True.

> > Not sure if servers.data type change is considered a breaking change.
> 
> Code before the upgrade (i.e. what we'd have to roll back to) throws an exception on startup which is what prompted me to create this issue.

Indeed, if schema is updated in later version, it will not necessarily work. It might, but it also may not.

I personally would like to keep the schema changes forward-only here. 1.19.0 will never know about downgrade path from 1.19.1 onwards.

**Comment by tysonstewart** [comment]
Understood. If I may offer a suggestion, an alternative to changing a column's type is to create a new column and duplicate values, writing to both old and new columns for a few versions. The old column can then be dropped at a later time. It allows for rollbacks if necessary.

Also, if the project followed [Semantic Versioning](https://semver.org/) it could give some heads-up about breaking changes because it requires major version number bumps.

Thank you both for your help and advice on this.

**Comment by azygis** [comment]
Yeah, that was my mistake back when I just changed the type. Completely missed a use case when server and client apps may be separate and out or sync with schema. Having a major version would have prevented that too as it's more visible that a bit more than some improvements were done.

Noted and (hopefully) not going to happen again.
